### ISSUE TITLE
How do I use in3 (Incubed) for Bash to view ethereum records for transactions beyond the most recent 400? 

### ISSUE THREAD

**Issue by a3845** [blockchainsllc/in3#31]
### Steps to reproduce
Run commands such as these with values greater than 200 (instead of 151 in the examples below):

```
in3 eth_getBlockByNumber latest false | jq '.transactions[151]'

in3 eth_getBlockByNumber latest true | jq '.transactions[151]'
```

### Expected behavior
I expect to see data from more than 400 different transactions.  I expect to be able to use integer values greater than 200.

### Actual behavior
I see "null" when the integer value is greater than 200.  Without the " | jq '.transactions..." syntax, I see maybe 175 transactions.

### System configuration
Ubuntu 18.04

#### Incubed version
3.0.0

#### Request
Allow for more transactions to be returned with in3 (not the most recent 400).

Irrelevantly, I noticed the word "envirmoent" is a typo here:  https://in3.readthedocs.io/en/develop/api-cmd.html

#### Chain
Ethereum

**Comment by simon-jentzsch** [comment]
the function `eth_getBlockByNumber` returns all transactions of the blockspecified, but currently there are about 200 transaction per block, so if you want to see more transactions, you need to fetch more blocks. Thie script will fetch 10 blocks (so the last about 2000 transactions)

```sh
BN=`in3 eth_blockNumber`; for ((i=$BN-10;i<=$BN;i++)); do in3 eth_getBlockByNumber $i false | jq -r '.transactions[]' ; done
```
