### ISSUE TITLE
Crash after IN3 runs for a while 

### ISSUE THREAD

**Issue by ligi** [blockchainsllc/in3#6]
This is on desktop with the jar from 2.1.0

# C  [libin3_jni.so+0x2209a]  d_type+0xa

[hs_err_pid28841.log](https://github.com/slockit/in3-c/files/4041215/hs_err_pid28841.log)

**Comment by simon-jentzsch** [comment]
@ligi   what OS or Distribution are you using?

**Comment by ligi** [comment]
Ubuntu 18.04.3 LTS

**Comment by cerealkill** [comment]
Hi @ligi and @omurovch, does it still crashes? We have new tests and ci to catch these issues, but we are not able to reproduce the issue.

**Comment by omurovch** [comment]
Hi @cerealkill,

Actually the issue #11 that I have created is not mentioning this issue #6. I have put stacktrace of the crash to to issue description, and it has numbering that uses hash tag. It seems github parsed those as references to issues. 

By the way, the crashes still happen, but much rarer. We use release v2.3.0. 

Regards.

**Comment by cerealkill** [comment]
Thanks for your support and feedback! We just released v3.0.1, and are wondering if this random crash still occurs.
